### ISSUE TITLE
Completions are nil for snippets

### ISSUE THREAD

**Issue by thorstengrothe** [elken/yasnippet-capf#21] opened 2024-04-20 14:41 UTC
Hi,

I like your package very much and use it every day. When I type a name of my snippet in the buffer it looks like this

![yasnippet](https://github.com/elken/yasnippet-capf/assets/19598706/cc3b0184-8098-4274-a248-4ef44fad1697)

For dabbrev it looks fine see here

![Dabbrev](https://github.com/elken/yasnippet-capf/assets/19598706/ab2947db-2c4e-4ff6-afc7-b503213ec07c)

Do you have an idea, what's going wrong?

Regards
Thorsten

**Comment by thorstengrothe** [comment] 2024-04-20 14:51
And another thing, if I press return, nothing happens. It worked in the past and I have no clue, what is going wrong. This is my config

`(use-package corfu
  :ensure t
  ;; :defer t
  :bind (:map corfu-map
              ;; ("M-SPC"      . corfu-insert-separator)
              ("M-k"        . corfu-next)
              ("M-i"        . corfu-previous)
              ;; ([backtab]    . corfu-previous)
              ;; ("S-<return>" . nil)
              ;; leave my entry as it is
              ("RET"        . corfu-expand))
  ;; Optional customizations
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto t)                 ;; Enable auto completion
  (corfu-separator ?\s)          ;; Orderless field separator
  (corfu-quit-no-match 'separator)
  ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
  ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
  (corfu-preview-current nil)    ;; Disable current candidate preview
  (corfu-preselect 'prompt)      ;; Preselect the prompt
  ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
  (corfu-scroll-margin 5)        ;; Use scroll margin

  :init
  (global-corfu-mode)
  :hook (before-save-hook . corfu-quit)
  :config
  (require 'corfu-history)
  (corfu-history-mode 1)
  (corfu-popupinfo-mode) ; Popup completion info
  (savehist-mode 1)
  (add-to-list 'savehist-additional-variables 'corfu-history)
  )`

`(use-package emacs
  :ensure nil
  :init
  ;; TAB cycle if there are only few candidates
  (setq completion-cycle-threshold 3)

  ;; Emacs 28: Hide commands in M-x which do not apply to the current mode.
  ;; Corfu commands are hidden, since they are not supposed to be used via M-x.
  ;; (setq read-extended-command-predicate
  ;;       #'command-completion-default-include-p)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (setq tab-always-indent 'complete)
  )`

`(use-package cape
  :ensure t
  :after corfu
  ;; Bind dedicated completion commands
  ;; Alternative prefix keys: C-c p, M-p, M-+, ...
  ;; :bind (("C-<tab>" . completion-at-point) ;; capf
  ;;        ("C-c p t" . complete-tag)        ;; etags
  ;;        ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
  ;;        ("C-c p h" . cape-history)
  ;;        ("C-c p f" . cape-file)
  ;;        ("C-c p k" . cape-keyword)
  ;;        ("C-c p s" . cape-symbol)
  ;;        ("C-c p a" . cape-abbrev)
  ;;        ("C-c p i" . cape-ispell)
  ;;        ("C-c p l" . cape-line)
  ;;        ("C-c p w" . cape-dict)
  ;;        ("C-c p \\" . cape-tex)
  ;;        ("C-c p _" . cape-tex)
  ;;        ("C-c p ^" . cape-tex)
  ;;        ("C-c p &" . cape-sgml)
  ;;        ("C-c p r" . cape-rfc1345))

  ;; Add `completion-at-point-functions', used by `completion-at-point'.
  ;; (add-to-list 'completion-at-point-functions #'cape-file)
  ;; (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  ;;(add-to-list 'completion-at-point-functions #'cape-history)
  ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
  ;; (add-to-list 'completion-at-point-functions #'cape-tex)
  ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
  ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
  ;; (add-to-list 'completion-at-point-functions #'cape-abbrev)
  ;; (add-to-list 'completion-at-point-functions #'cape-ispell)
  ;;(add-to-list 'completion-at-point-functions #'cape-dict)
  ;;(add-to-list 'completion-at-point-functions #'cape-symbol)
  ;;(add-to-list 'completion-at-point-functions #'cape-line)
  :config
  (defun thor-cape-capf-setup-elisp ()
    (let ((result))
      (dolist (element '(cape-file cape-dabbrev) result)
        (add-to-list 'completion-at-point-functions element))))

  (defun thor-cape-capf-setup-latex ()
    (let ((result))
      (dolist (element '(cape-file cape-dabbrev cape-tex) result)
        (add-to-list 'completion-at-point-functions element))))

  :hook
  (emacs-lisp-mode . thor-cape-capf-setup-elisp)
  (latex-mode . thor-cape-capf-setup-latex)
  (tex-mode . thor-cape-capf-setup-latex)
  )

(use-package yasnippet-capf
  :ensure (yasnippet-capf :type git :host github :repo "elken/yasnippet-capf")
  :after cape
  :init
  (add-to-list 'completion-at-point-functions #'yasnippet-capf)
  :config
  (setq yasnippet-capf-lookup-by 'name) ;; Prefer the name of the snippet instead
  )`

sorry for the double post :-)

**Comment by elken** [comment] 2024-04-20 15:12
> Hi,
> 
> I like your package very much and use it every day. 

Thanks very much :)

> Do you have an idea, what's going wrong?

Either the snippets you're using or have written are missing fields, or something has changed upstream in yasnippet. What do those `hydra-*` snippets look like?

**Comment by elken** [comment] 2024-04-20 15:35
Just pushed a fix that should fallback to resolve the first issue, but I do now suspect that improperly defined snippets are causing the second.

**Comment by thorstengrothe** [comment] 2024-04-20 16:18
Thanks for the super fast response. I updated the package with elpaca now it looks like this:

![hydranew](https://github.com/elken/yasnippet-capf/assets/19598706/d920a542-e0ab-4f4f-8296-24b127d17238)

I can see them but both snippets are not expandable when I press RET or SPACE

The hydra snippets look like this

```
# -*- mode: snippet -*-
#name : hydra
#key : hydra
#contributor : Thorsten Grothe
# --
(defhydra my/hydra-${1:name} (:color blue :hint nil)
"
"
("${2:letter}" ${3:command} "${4:Text}" :column "${5:column name}")

("q" nil "quit")
)

```
and

```
# -*- mode: snippet -*-
#name : hydra-spalte
#key : hydra
#contributor : Thorsten Grothe
# --
"${1:Titel Spalte}"
(
("$" ${2:Befehl} "${3:Name")

)

```

**Comment by thorstengrothe** [comment] 2024-04-20 16:28
Deleted the emacs-lisp-mode dir under snippets and made a new one

```
# -*- mode: snippet -*-
# name: defun
# key: defun
# --
(defun ${1:name} ()
  "${2:Describe function}"
  (interactive)
  (some-command)
  (some-other-command)
  )
```
Closed emacs and reopen an *.el file. Typed defun and nothing happens, the snippet not appears on the in buffer popup. Hm, strange....

Thanks for your help!

**Comment by elken** [comment] 2024-04-20 17:39
> Thanks for the super fast response. I updated the package with elpaca now it looks like this:
> 
> ![hydranew](https://private-user-images.githubusercontent.com/19598706/324190275-d920a542-e0ab-4f4f-8296-24b127d17238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzQ5MzUsIm5iZiI6MTcxMzYzNDYzNSwicGF0aCI6Ii8xOTU5ODcwNi8zMjQxOTAyNzUtZDkyMGE1NDItZTBhYi00ZjRmLTgyOTYtMjRiMTI3ZDE3MjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE3MzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGU2ODRlYjFjZGFhYTY4Yjg1OGQ1M2NlMzQ1ODNkZmI4M2ZlYmIzNDM0MDQ5YTBjNWYwODVjM2RkYmY4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m08AVgh7qMXDFMsGHK3N4VdEmjbzcCmDZvU6Src0ZrE)
> 
> I can see them but both snippets are not expandable when I press RET or SPACE
> 
> The hydra snippets look like this
> 
> ```
> # -*- mode: snippet -*-
> #name : hydra
> #key : hydra
> #contributor : Thorsten Grothe
> # --
> (defhydra my/hydra-${1:name} (:color blue :hint nil)
> "
> "
> ("${2:letter}" ${3:command} "${4:Text}" :column "${5:column name}")
> 
> ("q" nil "quit")
> )
> ```
> 
> and
> 
> ```
> # -*- mode: snippet -*-
> #name : hydra-spalte
> #key : hydra
> #contributor : Thorsten Grothe
> # --
> "${1:Titel Spalte}"
> (
> ("$" ${2:Befehl} "${3:Name")
> 
> )
> ```

Imagine with these you need a space between the `#` and the key name.

As for the second issue, you might have to call `M-x yas-reload-all` first.

**Comment by thorstengrothe** [comment] 2024-04-20 18:07
> Imagine with these you need a space between the # and the key name.

> As for the second issue, you might have to call M-x yas-reload-all first.

I fixed the space in all my snippets and reloaded everything. It helps nothing it does not work. Now I get no popup completion in my buffer and can expand nothing. Hm, something is going wrong here 😊

**Comment by elken** [comment] 2024-04-20 18:13
I can't reproduce this. Have included a webm demo below with one of your snippets saved as below

```lisp
# -*- mode: snippet -*-
# name : hydra
# key : hydra
# --
(defhydra my/hydra-${1:name} (:color blue :hint nil)
"
"
("${2:letter}" ${3:command} "${4:Text}" :column "${5:column name}")

("q" nil "quit")
)
```

[Screencast from 2024-04-20 19-12-01.webm](https://github.com/elken/yasnippet-capf/assets/2872862/acdccd5a-f5d2-4d62-8f17-42844992b7b4)

Sounds like you've perhaps got issues with your yasnippet setup in that case :frowning_face:

**Comment by thorstengrothe** [comment] 2024-04-20 18:21
Thank you, I see. I believe I got something.

When I type the name of the snippet and hit TAB nothing happens. When I thereafter hit `M-X` and call `yasnippet-capf` in the minibuffer I got the popups showing me snippets. 

Now I can hit TAB and the snippet is expanding. So I guess it has something to do with the keybinding. In Cape I set `:bind (("<tab>" . completion-at-point) `. 

In Yasnippet-Capf I set nothing, is this the problem?

**Comment by elken** [comment] 2024-04-20 18:29
No, all the package does is feed the data into Corfu so it can complete it as normal.

Corfu already maps `<tab>` as needed, so unless you have a specific reason to bind that globally then I would probably say don't.

**Comment by thorstengrothe** [comment] 2024-04-20 19:39
Ok I setup my packages to a minimum

Vertico, consult and orderless are disabled.

```
(use-package yasnippet
  :commands (yas-global-mode)
  :init
  (yas-global-mode)
  :config
  (setq yas-snippet-dirs '("~/.emacs.d/snippets"))
  )
```
```
(use-package corfu
  :ensure t
  )

(use-package cape
  :ensure t
  :after corfu
  )

(use-package yasnippet-capf
  :ensure (yasnippet-capf :type git :host github :repo "elken/yasnippet-capf")
  :after cape
  :init
  (add-to-list 'completion-at-point-functions #'yasnippet-capf)
  :config
  (setq yasnippet-capf-lookup-by 'name) ;; Prefer the name of the snippet instead
  )

```
I setup two snippets for emacs-lisp-mode in a new empty snippet dir.

```
# -*- mode: snippet -*-
# name: lorem
# key: lorem
# --
blabkla

# -*- mode: snippet -*-
# name: test
# key: test
# --
test lorem lorem lorem lorem
```
Open an *.el file

Enter test --> snippet expands 
Enter lorem --> snippet expands

But without popup in my file, it expands silently, nothing else. What I want is a popup in my buffer like in your small video. 

Hm, what I'm doing wrong?

**Comment by elken** [comment] 2024-04-21 04:40
I don't know, but it seems like the issue is with your config which unfortunately I can't debug.

If you're able to find a reproducible case that proves this package is at fault then please do submit another issue, otherwise I think this one can be closed for now.

**Closed by elken** 2024-04-21 04:40 UTC
